### ISSUE TITLE
Errors during "doco up -d"

### ISSUE THREAD

**Issue by ilevennet** [magenx/Magento-2-docker-configuration#2]
When run the command
`doco up -d`
docker build rabbit and Redis container with standard name instead BRAND-service

`doco up -d
Creating volume "magenx_magento" with default driver
Creating volume "magenx_ssl" with default driver
Creating volume "magenx_mariadb" with default driver
Creating volume "magenx_mariadbcnf" with default driver
Creating volume "magenx_phpmyadmin" with default driver
Creating volume "magenx_phpmyadmincfg" with default driver
Creating volume "magenx_elasticsearch" with default driver
Creating volume "magenx_certbot" with default driver
Creating volume "magenx_certbotlib" with default driver
Creating volume "magenx_nginx" with default driver
Creating volume "magenx_varnish" with default driver
Pulling redis-cache (redis:6.2.6-alpine)...
6.2.6-alpine: Pulling from library/redis
...
211a7f52febb: Pull complete
Status: Downloaded newer image for redis:6.2.6-alpine
Pulling rabbitmq (rabbitmq:3.8-alpine)...
3.8-alpine: Pulling from library/rabbitmq
...
00e933ffa161: Pull complete
Status: Downloaded newer image for rabbitmq:3.8-alpine
Pulling phpmyadmin (phpmyadmin:fpm-alpine)...
fpm-alpine: Pulling from library/phpmyadmin
...
3c68c5868dbc: Pull complete
Status: Downloaded newer image for phpmyadmin:fpm-alpine
Pulling certbot (certbot/certbot:latest)...
...
39de151aab4: Pull complete
...
Status: Downloaded newer image for certbot/certbot:latest
Creating magenx-certbot       ... error
Creating magenx-mariadb ...
Creating magenx-redis-cache ...
Creating magenx-magento     ...
Creating magenx-redis-cache   ... error
Creating magenx-redis-session ...
Creating magenx-rabbitmq      ...

ERROR: for magenx-certbot  Cannot create container for service certbot: stat /dev/log: no such file or directory
Creating magenx-mariadb       ... error
Creating magenx-elasticsearch ... error

ERROR: for magenx-redis-session  Cannot create container for service redis-session: stat /dev/log: no such file or directory
Creating magenx-magento       ... error
ERROR: for magenx-elasticsearch  Cannot create container for service elasticsearch: stat /dev/log: no such file or directory

ERROR: for magenx-mariadb  Cannot create container for service mariadb: stat /dev/log: no such file or directory

Creating magenx-rabbitmq      ... error

ERROR: for magenx-rabbitmq  Cannot create container for service rabbitmq: stat /dev/log: no such file or directory

ERROR: for certbot  Cannot create container for service certbot: stat /dev/log: no such file or directory

ERROR: for redis-cache  Cannot create container for service redis-cache: stat /dev/log: no such file or directory

ERROR: for redis-session  Cannot create container for service redis-session: stat /dev/log: no such file or directory

ERROR: for elasticsearch  Cannot create container for service elasticsearch: stat /dev/log: no such file or directory

ERROR: for mariadb  Cannot create container for service mariadb: stat /dev/log: no such file or directory

ERROR: for magento  Cannot create container for service magento: stat /dev/log: no such file or directory

ERROR: for rabbitmq  Cannot create container for service rabbitmq: stat /dev/log: no such file or directory
ERROR: Encountered errors while bringing up the project.
 `

**Comment by magenx** [comment]
you can use syslog or configure default logger
