### ISSUE TITLE
magenx-cron internal error

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-docker-configuration#3]
On running `doco up -d`
```
 > [magenx-cron internal] load metadata for docker.io/library/magenx_php:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
On Rocky Linux 9

**Comment by oodyboo** [comment]
I got past this error with the following change to 3 Dockerfiles:
cron/Dockerfile
composer/Dockerfile
magento/Dockerfile

Change line 2 to :  `FROM --platform=linux/amd64 ${BRAND}-php`

platform argument forces docker to load a local image, and I also changed the _php to -php to match the image file in my docker list.

also in varnish/Dockerfile I had to add
`USER root`
( before the RUN command)
this got me past a permission error running apk commands

Now I'm stuck at the xlogger service
Changed docker-compose.yml  /dev/log to /var/log:

`syslog-address: "unixgram:///var/log/"`

And I'm getting:
Error response from daemon: failed to initialize logging driver: dial unixgram /var/log/: connect: connection refused

**Comment by magenx** [comment]
https://docs.docker.com/config/containers/logging/syslog/

you can use default docker logs
but in config you must have syslog running and listening on that socket
like rsyslog syslogd etc

```
root@server:~# ls -l /dev/log
lrwxrwxrwx 1 root root 28 Nov 28 12:27 /dev/log -> /run/systemd/journal/dev-log
```
